services:
  - type: web
    name: telegram-facebook-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        value: 8810032339:AAEd_QXFwxWKcAFFZGPryfcuGiFMJOoSCNg
      - key: ADMIN_ID
        value: 7706183809
      - key: PORT
        value: 3000
